info:
  app:
    name: "spike-load-csv"
    description: "Spike Load Big CSV in memory"

server:
  port: 8080
  servlet:
    context-path: /

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricing
    password: postgres
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql

logging:
  level:
    root: INFO
    br:
      com:
        creditas:
          spikeloadtable: INFO
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: DEBUG

# Files at resources folder
csv:
  autoload: true
  path: csv/table.csv
